# Generated by Django 2.1.3 on 2019-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerdiscount',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
