# Generated by Django 2.1.3 on 2019-01-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.Outlet'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.AckodriveQuote'),
        ),
        migrations.AddField(
            model_name='booking',
            name='testdrive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Testdrive'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='ackodrivedicsount_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.AckodriveDiscount'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='dealerdiscount_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.DealerDiscount'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='insurancetype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.InsuranceType'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='outlet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Outlet'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='price_config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.PriceConfig'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='pricetype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.PriceType'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='rto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Rto'),
        ),
        migrations.AddField(
            model_name='ackodrivequote',
            name='variant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Variant'),
        ),
        migrations.AddField(
            model_name='ackodrivekindoffers',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.City'),
        ),
        migrations.AddField(
            model_name='ackodrivekindoffers',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Variant'),
        ),
        migrations.AddField(
            model_name='ackodrivediscount',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.City'),
        ),
        migrations.AddField(
            model_name='ackodrivediscount',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Variant'),
        ),
    ]
