# Generated by Django 2.1.3 on 2018-12-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdm',
            name='alt_contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bdm',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no_1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no_2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
