# Generated by Django 2.1.3 on 2019-01-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20190107_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dealer.Brand'),
        ),
    ]
