# Generated by Django 2.1.3 on 2019-01-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20190108_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='ackodrivediscount',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.City'),
        ),
        migrations.AddField(
            model_name='ackodrivekindoffers',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.City'),
        ),
    ]
