# Generated by Django 2.1.3 on 2018-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20181124_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
