# Generated by Django 2.1.3 on 2018-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_dealer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdm',
            name='alt_contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
