# Generated by Django 2.1.3 on 2018-12-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.IntegerField(),
        ),
    ]
