# Generated by Django 2.1.3 on 2018-12-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_auto_20181230_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDiscountUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('variant_name', models.CharField(max_length=50)),
                ('cash_discount', models.IntegerField()),
                ('non_cash_offer', models.IntegerField()),
            ],
        ),
    ]
