# Generated by Django 2.1.3 on 2018-11-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_auto_20181124_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='sales_outlet',
            field=models.BooleanField(default=True),
        ),
    ]
