# Generated by Django 2.1.3 on 2018-12-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_auto_20181230_0456'),
        ('dealer', '0003_dealerdiscountupload'),
    ]

    operations = [
    ]
