# Generated by Django 2.1.3 on 2018-12-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_dealerdiscountupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='body',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='seating_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='transmission_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.TransmissionType'),
        ),
    ]
