# Generated by Django 2.1.3 on 2018-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_auto_20181231_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
