# Generated by Django 2.1.3 on 2018-11-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_contact_is_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='area',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
