# Generated by Django 2.1.3 on 2018-11-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_auto_20181126_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
