# Generated by Django 2.1.3 on 2019-01-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0008_auto_20190101_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.TextField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Variant')),
            ],
        ),
        migrations.RenameField(
            model_name='ackodrivekindoffers',
            old_name='type',
            new_name='offers',
        ),
    ]
