# Generated by Django 2.1.3 on 2018-11-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0008_outlet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
    ]
