# Generated by Django 2.1.3 on 2019-01-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0009_auto_20190102_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerdiscount',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.City'),
        ),
        migrations.AddField(
            model_name='dealeroffer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.City'),
        ),
    ]
