# Generated by Django 2.1.3 on 2018-12-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_model_transmissiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rto_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cc', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('iscorporatediscount', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Model')),
                ('transmission_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.TransmissionType')),
            ],
        ),
        migrations.AddField(
            model_name='dealerdiscount',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Variant'),
        ),
    ]
