# Generated by Django 2.1.3 on 2018-12-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_ackodrivediscount_ackodrivekindoffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_till', models.DateField()),
                ('ex_showroom', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('environment_compensation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('octroi', models.CharField(max_length=50)),
                ('rsa_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extended_warranty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('govt_employee_scheme', models.CharField(max_length=50)),
                ('corporate_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_accessories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_plate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('smart_card', models.CharField(max_length=50)),
                ('mcd_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_collected_at_source', models.DecimalField(decimal_places=2, max_digits=10)),
                ('road_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logistic_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nexa_card', models.CharField(max_length=50)),
                ('honda_connect', models.CharField(max_length=50)),
                ('honda_genius_access', models.CharField(max_length=50)),
                ('fast_tag', models.CharField(max_length=50)),
                ('ackodrive_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.AckodriveDiscount')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.InsuranceType')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.PriceType')),
                ('rto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Rto')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Variant')),
            ],
        ),
    ]
