# Generated by Django 2.1.3 on 2018-12-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0013_priceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerKindOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BestPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MarketPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.PriceConfig')),
            ],
        ),
    ]
