# Generated by Django 2.1.3 on 2018-12-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0014_dealerkindoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AckodriveQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('corporatediscount_id', models.BigIntegerField()),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('ackodrivedicsount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.AckodriveDiscount')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer')),
                ('dealerdiscount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.DealerDiscount')),
                ('insurancetype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.InsuranceType')),
                ('outlet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Outlet')),
                ('price_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.PriceConfig')),
                ('pricetype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.PriceType')),
                ('rto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Rto')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Variant')),
            ],
        ),
    ]
