# Generated by Django 2.1.3 on 2018-12-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0016_auto_20181208_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50)),
                ('okind', models.CharField(max_length=50)),
                ('oid', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pg', models.CharField(max_length=100)),
                ('pg_token', models.CharField(max_length=100)),
                ('pg_response', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=30)),
                ('payment_on', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=30)),
                ('order_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(max_length=30)),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Booking')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.AckodriveQuote')),
            ],
        ),
    ]
