# Generated by Django 2.1.3 on 2018-12-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0017_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
