# Generated by Django 2.1.3 on 2018-12-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0019_dealerpricefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerpricefile',
            name='file',
            field=models.FileField(upload_to='./dealerprice'),
        ),
    ]
