# Generated by Django 2.1.3 on 2018-12-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0021_auto_20181213_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
