# Generated by Django 2.1.3 on 2018-12-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0022_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
